sorting/urls.py
from django.urls import path
from . import views

app_name = 'sorting'
urlpatterns = [
    path('', views.Sort.as_view(), name='main'),
    path('results', views.upload_txt, name='results'),
]

sorting_algorithms/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sorting.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sorting/models.py
from django.db import models


ALGORITHMS_SORT = [
    ('Bubble', 'Bubble sorting'),
    ('Insertion', 'Insertion sorting'),
    ('Merge', 'Merge sorting'),
]


class Sorting(models.Model):
    title = models.CharField(max_length=100, choices=ALGORITHMS_SORT)
    execution_time = models.CharField(max_length=100, default=0.0)
    upload_file = models.FileField(default='')
    sorted_file = models.FileField(default='')
    date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return '{}_{}'.format(self.title, self.date)

sorting/forms.py
from .models import Sorting
from django.forms import ModelForm


class SortingForm(ModelForm):
    class Meta:
        model = Sorting
        fields = ['title', 'upload_file']

sorting/views.py
from django.conf import settings
from django.shortcuts import render
from django.views.generic import FormView
from .forms import SortingForm
from .models import Sorting
from .sort_algorithms import Bubble, Insertion, Merge


import datetime
import os
import sys


class Sort(FormView):
    template_name = 'sorting/index.html'
    form_class = SortingForm
    success_url = '/results/'


def str_to_class(classname):
    return getattr(sys.modules[__name__], classname)


def upload_txt(request):
    date = datetime.datetime.now().strftime('%Y%m%d%H%M%S')
    algorithm = str_to_class(request.POST['title'])
    txt_input = request.FILES['upload_file']
    txt_input_data = txt_input.read().decode('utf-8')
    file_input = '{}_{}'.format(date, txt_input.name)

    if not os.path.isdir(os.path.join(settings.BASE_DIR, 'result')):
        os.mkdir(os.path.join(settings.BASE_DIR, 'result'))

    with open(os.path.join(settings.MEDIA_ROOT, file_input), 'w') as f:
        # save downloaded file
        f.write(txt_input_data)

    B = algorithm(txt_input_data)
    B.read()

    log_time = {}
    B.sort(log_time=log_time)

    results = B.print_()

    file_output_name = f'result_{txt_input.field_name}_{date}.txt'

    with open(os.path.join(settings.MEDIA_ROOT, file_output_name), 'w') as f:
        f.writelines(', '.join([str(i) for i in results]))

    time_exec = log_time.get('sort', 0.0)

    r = Sorting(
        title=request.POST['title'],
        execution_time=time_exec,
        upload_file=file_input,
        sorted_file=file_output_name
    )
    r.save()

    return render(request, 'sorting/result.html', {
        'input_file_url': settings.MEDIA_URL + file_input,
        'input_file_name': txt_input.name,
        'input_list': [int(i) for i in txt_input_data.split(',')],
        'output_file_url': settings.MEDIA_URL + file_output_name,
        'output_file_name': f'result_{txt_input.name}',
        'output_list': results,
        'time_execution': time_exec,
        })

sorting/templates/sorting/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %}{% endblock %}</title>
</head>
<body>
  <a href="{% url 'sorting:main' %}"><h1>Sorting algorithms</h1></a>
  {% block content %}
  {% endblock %}
</body>
</html>

sorting/templates/sorting/index.html
{% extends 'sorting/base.html' %}


{% block title %}
    Sorting Algorithms
{% endblock %}

{% block content %}
    <p><strong>*please, upload file with comma delimiter</strong></p>
    <form action="{% url 'sorting:results' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.upload_file }}
        {{ form.title }}
        <input type="submit" value="Process">
    </form>
{% endblock %}

sorting/templates/sorting/result.html
{% extends 'sorting/base.html' %}

{% block title %}
    Sorting Algorithms -- Result
{% endblock %}

{% block content %}
    <h1>Result:</h1>
    <a href="{{ input_file_url }}" target="_blank">{{ input_file_name }}</a></p>
    <p>{{ input_list|slice:":25" }}</p>
    <a href="{{ output_file_url }}" target="_blank">{{ output_file_name }}</a></p>
    <p>{{ output_list|slice:":25" }}</p>
    <p>Execution time: {{ time_execution }}</p>
{% endblock %}